spring:
  application:
    name: hello-spring-cloud-zuul

  #服务监控客户端配置
  boot:
    admin:
      client:
        url: http://localhost:8084
  #因为该服务需要被追踪，所以要开启追踪
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8769

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/  #服务的发现注册中心地址

zuul:
  routes:  # api网关聚合两个服务
    api-a:
      path: /api/a/**  # **表示全目录匹配
      serviceId: hello-spring-cloud-web-admin-feign # 服务的名字
    api-b:
      path: /api/b/**
      serviceId: hello-spring-cloud-web-admin-ribbon

#  其实在配置完这个配置文件后，其实zuul已经实现了反向代理和负载均衡的两个功能了，
#  可能有人这时候就纳闷了，这里不是只是反向代理了吗？怎么实现负载均衡呢？
#  其实zuul实现负载均衡很简单，使用serviceId进行绑定后，
#  如果有多个相同的serviceid，则会进行轮询的方式进行访问。