spring:
  cloud:
    config:
      uri: http://localhost:8888 # spring cloud配置中心地址
      name: web-admin-feign  # 配置文件名
      label: master # 分支
      profile: prod # 激活那个配置 -prod

### 启动说明
   # spring默认装载的是application.yml
   # 我们启动时可以指定配置文件
   # 命令： java -jar xxx.jar --spring.profiles.active=prod

  #如果使用的docker部署：
  #在docker中的profile 我们可以指定 [cmd] 指定启动参数
